package muxtool

import (
	"net/http"
	"strconv"
)

// ProblemDetails is Problem Details for HTTP APIs.
// RFC7807 https://www.rfc-editor.org/rfc/rfc7807
type ProblemDetails struct {
	// Type A URI reference [RFC3986] that identifies the problem type. This specification
	// encourages that, when dereferenced, it provide human-readable documentation for
	// the problem type (e.g., using HTML [W3C.REC-html5-20141028]).
	// When this member is not present, its value is assumed to be "about:blank".
	Type string `json:"type" xml:"type"`

	// Title A short, human-readable summary of the problem type.  It SHOULD NOT change from
	// occurrence to occurrence of the problem, except for purposes of localization (e.g., using
	// proactive content negotiation; see [RFC7231], Section 3.4).
	Title string `json:"title" xml:"title"`

	// Status The HTTP status code ([RFC7231], Section 6) generated by the origin server for
	// this occurrence of the problem.
	Status int `json:"status" xml:"status"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail" xml:"detail"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string `json:"instance" xml:"instance"`
}

func (d ProblemDetails) String() string {
	return "problem detail, type='" + d.Type + "'" +
		", title='" + d.Title + "'" +
		", status=" + strconv.FormatInt(int64(d.Status), 10) +
		", detail='" + d.Detail + "'" +
		", instance='" + d.Instance + "'"
}

type ResponseError struct {
	Request *http.Request
	RawBody []byte
	Details *ProblemDetails
}

func (r *ResponseError) Error() string {
	if r.Details != nil {
		return r.Details.String()
	}
	status := strconv.FormatInt(int64(r.Request.Response.StatusCode), 10)

	return "response error, host='" + r.Request.Host + "'" +
		", method='" + r.Request.Method + "'" +
		", instance='" + r.Request.RequestURI + "'" +
		", status=" + status +
		", body='" + string(r.RawBody) + "'"
}
